// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOppNLQ7pQCj5L8HCUgZmSyDwTifpuQFM',
    appId: '1:628514980973:web:2ad2ddf0e18cf2c8536b64',
    messagingSenderId: '628514980973',
    projectId: 'rapidcare-275a1',
    authDomain: 'rapidcare-275a1.firebaseapp.com',
    storageBucket: 'rapidcare-275a1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOqwWRbu7Dcw1RTETlG16LOWnbn6uVqGk',
    appId: '1:628514980973:android:4cb2ec269cc79210536b64',
    messagingSenderId: '628514980973',
    projectId: 'rapidcare-275a1',
    storageBucket: 'rapidcare-275a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYXqQlmxtWaBLW1hAaNZzlCRbrqzdQXy8',
    appId: '1:628514980973:ios:e66d019a2342f338536b64',
    messagingSenderId: '628514980973',
    projectId: 'rapidcare-275a1',
    storageBucket: 'rapidcare-275a1.firebasestorage.app',
    iosBundleId: 'com.example.rapidcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYXqQlmxtWaBLW1hAaNZzlCRbrqzdQXy8',
    appId: '1:628514980973:ios:e66d019a2342f338536b64',
    messagingSenderId: '628514980973',
    projectId: 'rapidcare-275a1',
    storageBucket: 'rapidcare-275a1.firebasestorage.app',
    iosBundleId: 'com.example.rapidcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOppNLQ7pQCj5L8HCUgZmSyDwTifpuQFM',
    appId: '1:628514980973:web:1ab5ab806b3ad6e1536b64',
    messagingSenderId: '628514980973',
    projectId: 'rapidcare-275a1',
    authDomain: 'rapidcare-275a1.firebaseapp.com',
    storageBucket: 'rapidcare-275a1.firebasestorage.app',
  );
}
